# Generated by Django 5.2.6 on 2025-09-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
