# Generated by Django 5.2.6 on 2025-09-20 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0002_alter_taskgroup_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskgroup',
            old_name='name',
            new_name='title',
        ),
    ]
